import Logo from "./logo";

type Props = { kicker:string; title:string; accent:string; intro:string; facts:{value:string;label:string}[]; what:string; steps:{n:string,title:string,text:string}[]; benefits:string[]; fit:string[]; legal?:boolean };

export default function Vertriebsweg({kicker,title,accent,intro,facts,what,steps,benefits,fit,legal}:Props) {
  const visuals:Record<string,{image:string;alt:string;label:string}> = {
    "Cold Calling": {image:"/media/leon-call.jpg",alt:"Telefonische Kundenansprache auf einer Terrasse",label:"B2B-Gespräche flexibel und ortsunabhängig führen"},
    "Door-to-Door": {image:"/media/d2d-mobile.jpg",alt:"Mobiler Arbeitstag mit Laptop unterwegs",label:"Deutschlandweit unterwegs und nah am Kunden"},
    "Teamaufbau": {image:"/media/mentoring.jpg",alt:"Persönlicher Austausch und Mentoring",label:"Erfahrung weitergeben und Menschen persönlich entwickeln"},
  };
  const {image,imageAlt,imageLabel} = {image:visuals[title].image,imageAlt:visuals[title].alt,imageLabel:visuals[title].label};
  return <main className="pathPage">
    <header className="pathNav"><a className="brand" href="/"><Logo/><b>VERTRIEB</b></a><a href="/#wege">← Alle Vertriebswege</a><a className="navCta" href="/bewerbung">Potenzial prüfen ↗</a></header>
    <section className="pathHero"><div className="pathHeroImage"><img src={image} alt={imageAlt}/><span>{imageLabel}</span></div><div className="grid"/><small>{kicker}</small><h1>{title}<br/><em>{accent}</em></h1><p>{intro}</p><a className="btn lime" href="/bewerbung">Kostenlos kennenlernen ↗</a><div className="pathFacts">{facts.map(x=><span key={x.label}><b>{x.value}</b>{x.label}</span>)}</div></section>
    <section className="pathWhat"><small>KLAR ERKLÄRT</small><div><h2>Was bedeutet<br/>{title}?</h2><div><p>{what}</p>{title==="Cold Calling"&&<aside><b>Rechtlicher Rahmen:</b> Werbeanrufe erfolgen nicht wahllos. Gegenüber Unternehmen ist nach § 7 Abs. 2 Nr. 1 UWG zumindest eine mutmaßliche Einwilligung erforderlich, die anhand konkreter Umstände vor dem Anruf geprüft und dokumentiert werden muss. Verbraucher werden nicht ohne vorherige ausdrückliche Einwilligung angerufen.</aside>}{title==="Door-to-Door"&&<aside><b>Verbraucherschutz:</b> Ein Nein wird respektiert. Bei außerhalb von Geschäftsräumen geschlossenen Verbraucherverträgen sind die gesetzlichen Informations- und Widerrufsrechte, insbesondere nach §§ 312g, 355 BGB, einzuhalten. Vertragsunterlagen und Widerrufsbelehrung müssen korrekt bereitgestellt werden.</aside>}</div></div></section>
    <section className="pathProcess"><div className="sectionHead"><span>DER ABLAUF</span><span>SCHRITT FÜR SCHRITT</span></div><div>{steps.map(x=><article key={x.n}><b>{x.n}</b><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>
    <section className="pathSplit"><div><small>WAS DU BEKOMMST</small><h2>Struktur statt<br/>Alleingang.</h2><ul>{benefits.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>WAS DU MITBRINGST</small><h2>Passt das<br/>zu dir?</h2><ul>{fit.map(x=><li key={x}>{x}</li>)}</ul></div></section>
    {legal&&<section className="legalModel"><small>RECHTLICH SAUBER GEDACHT</small><h2>Teamaufbau ist nicht automatisch<br/><em>ein verbotenes System.</em></h2><div><p>Im Handelsvertreterrecht ist selbstständige Vermittlung gegen Provision grundsätzlich vorgesehen. Entscheidend ist aber die konkrete Ausgestaltung: Vergütung soll an echte vermittelte beziehungsweise ausgeführte Geschäfte anknüpfen – nicht allein daran, neue Teilnehmer anzuwerben oder Eintrittszahlungen zu erzeugen.</p><p>Unser beschriebenes Modell basiert deshalb auf realem Strom- und Gasvertrieb, klaren Verträgen, dokumentierten Leistungen und vertraglich geregelten Provisionen. Die Anzahl möglicher Führungsebenen allein entscheidet nicht über die Rechtmäßigkeit; maßgeblich sind Vergütungsgrund, Transparenz und tatsächliche Durchführung.</p></div><div className="lawLinks"><a href="https://www.gesetze-im-internet.de/hgb/__84.html" target="_blank" rel="noreferrer">§ 84 HGB · Handelsvertreter ↗</a><a href="https://www.gesetze-im-internet.de/hgb/__87.html" target="_blank" rel="noreferrer">§ 87 HGB · Provision ↗</a><a href="https://www.gesetze-im-internet.de/uwg_2004/__16.html" target="_blank" rel="noreferrer">§ 16 UWG · Verbotene progressive Kundenwerbung ↗</a></div><aside>Diese allgemeine Einordnung ist keine individuelle Rechtsberatung. Maßgeblich sind immer die konkreten Verträge, Zahlungsflüsse und die tatsächliche Umsetzung.</aside></section>}
    <section className="final"><small>DEIN NÄCHSTER SCHRITT</small><h2>Erst kennenlernen.<br/>Dann entscheiden.</h2><a className="btn lime" href="/bewerbung">Jetzt Potenzial prüfen ↗</a></section>
    <footer><a className="brand" href="/"><Logo/><b>VERTRIEB</b></a><div><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a></div><p>Selbstständige Tätigkeit auf Provisionsbasis. Keine Einkommensgarantie.</p></footer>
  </main>;
}
