export default function Datenschutz(){return <main className="legal"><a href="/">← Zurück</a><small>RECHTLICHES</small><h1>Datenschutzerklärung</h1>
<h2>1. Verantwortlicher</h2><p><strong>Leon Schüßler &amp; Justin Rother GbR</strong><br/>Erich-Wolf-Straße 10, 63840 Hausen, Deutschland<br/>Telefon: <a href="tel:+491716327501">+49 171 6327501</a><br/>E-Mail: <a href="mailto:info@jl-vertrieb.com">info@jl-vertrieb.com</a></p>
<h2>2. Allgemeines</h2><p>Wir verarbeiten personenbezogene Daten nur, soweit dies zur Bereitstellung dieser Website, zur Bearbeitung von Anfragen, zur Durchführung vorvertraglicher Maßnahmen oder zur Erfüllung gesetzlicher Pflichten erforderlich ist. Personenbezogene Daten sind alle Informationen, die sich auf eine identifizierte oder identifizierbare Person beziehen.</p>
<h2>3. Hosting und Server-Protokolle</h2><p>Diese Website wird über ChatGPT Sites von OpenAI Ireland Limited, 1st Floor, The Liffey Trust Centre, 117–126 Sheriff Street Upper, Dublin 1, D01 YC43, Irland, bereitgestellt. Beim Aufruf können insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene Seite, Referrer, Browser-, Geräte- und Betriebssysteminformationen sowie technische Statusdaten verarbeitet werden. Die Verarbeitung dient der sicheren und funktionsfähigen Bereitstellung der Website. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in Betrieb, Sicherheit und Fehleranalyse. OpenAI kann Unterauftragsverarbeiter einsetzen. Soweit Daten in Drittländer übermittelt werden, erfolgt dies nach Maßgabe der Art. 44 ff. DSGVO, insbesondere auf Grundlage eines Angemessenheitsbeschlusses oder geeigneter Garantien.</p>
<h2>4. Eigene Cookies und Analyse</h2><p>Wir setzen auf dieser Website keine eigenen Analyse-, Marketing- oder Tracking-Dienste ein. Technisch notwendige Speicherungen oder Cookies des Hostinganbieters können zur Auslieferung, Sicherheit oder Zugriffskontrolle erforderlich sein. Rechtsgrundlage ist § 25 Abs. 2 Nr. 2 TDDDG; die anschließende Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.</p>
<h2>5. Online-Energie-Check</h2><p>Beim Online-Energie-Check verarbeiten wir Name, E-Mail-Adresse, Lieferadresse, Energieart, Jahresverbrauch, Arbeits- und Grundpreis sowie die dazu ausgewählten Preisangaben. Zweck ist die Prüfung deiner Anfrage, die Vorbereitung eines möglichen Angebots und die persönliche Kontaktaufnahme. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO, soweit die Verarbeitung auf deine Anfrage hin zur Durchführung vorvertraglicher Maßnahmen erfolgt. Pflichtangaben sind für die gewünschte Prüfung erforderlich; ohne sie können wir den Online-Check nicht bearbeiten.</p>
<h2>6. Formularübermittlung über FormSubmit</h2><p>Für die technische Übermittlung des Online-Formulars verwenden wir FormSubmit, einen externen Formular- und E-Mail-Weiterleitungsdienst. Die eingegebenen Daten werden an FormSubmit übermittelt und von dort an <a href="mailto:info@jl-vertrieb.com">info@jl-vertrieb.com</a> weitergeleitet. Dabei können auch technische Verbindungsdaten verarbeitet werden. Rechtsgrundlage für die Übermittlung ist Art. 6 Abs. 1 lit. b DSGVO. Da bei externen Diensten eine Verarbeitung außerhalb der EU bzw. des EWR nicht ausgeschlossen werden kann, können Risiken bestehen, etwa ein abweichendes Datenschutzniveau oder behördliche Zugriffsmöglichkeiten. Weitere Informationen enthält die <a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noreferrer">Datenschutzerklärung von FormSubmit</a>.</p>
<h2>7. Kontakt über WhatsApp</h2><p>Wenn du die WhatsApp-Option auswählst, wirst du zu einem Angebot von WhatsApp weitergeleitet. Anbieter im Europäischen Wirtschaftsraum ist grundsätzlich WhatsApp Ireland Limited, Merrion Road, Dublin 4, D04 X2K5, Irland. Erst mit dem Anklicken verlässt du diese Website. WhatsApp verarbeitet dabei eigene Nutzungs-, Kontakt-, Geräte- und Metadaten; eine Übermittlung in Drittländer kann nicht ausgeschlossen werden. Wenn du uns über WhatsApp kontaktierst, verarbeiten wir deine Telefonnummer, Profilinformationen, Nachrichten und freiwillig gesendete Unterlagen zur Bearbeitung deiner Anfrage auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO. Nutze alternativ E-Mail, wenn du WhatsApp nicht verwenden möchtest.</p>
<h2>8. Bewerbungs- und Potenzial-Check</h2><p>Die Antworten und die Punkteauswertung des Potenzial-Checks werden ausschließlich lokal in deinem Browser verarbeitet und nicht an uns oder Dritte übermittelt. Es findet keine ausschließlich automatisierte Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung im Sinne von Art. 22 DSGVO statt. Erst wenn du anschließend freiwillig WhatsApp öffnest und eine Nachricht sendest, werden personenbezogene Daten nach Maßgabe des vorstehenden Abschnitts verarbeitet.</p>
<h2>9. Direkter Kontakt per E-Mail oder Telefon</h2><p>Bei einer Kontaktaufnahme verarbeiten wir deine Kontaktdaten und den Inhalt deiner Nachricht zur Bearbeitung des Anliegens. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO bei vorvertraglichen oder vertraglichen Anfragen, andernfalls Art. 6 Abs. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt in einer geordneten Kommunikation.</p>
<h2>10. Empfänger</h2><p>Empfänger können neben den genannten technischen Dienstleistern unsere intern zuständigen Personen sowie – nur soweit für die Anfrage erforderlich – beteiligte Energie-, Vertriebs- oder Kooperationspartner sein. Eine Weitergabe zu anderen Zwecken erfolgt nur mit Rechtsgrundlage oder gesetzlicher Verpflichtung. Vor einer Weiterleitung an einen konkreten Anbieter informieren wir über den vorgesehenen Ablauf.</p>
<h2>11. Speicherdauer</h2><p>Wir löschen personenbezogene Daten, sobald der jeweilige Zweck entfällt und keine gesetzlichen Aufbewahrungs- oder Nachweispflichten entgegenstehen. Nicht zum Vertrag führende Anfragen werden grundsätzlich spätestens zwölf Monate nach Abschluss der Bearbeitung gelöscht, sofern keine Einwilligung für eine längere Kommunikation erteilt wurde oder Ansprüche zu sichern sind. Vertrags- und abrechnungsrelevante Unterlagen können entsprechend handels- und steuerrechtlicher Fristen länger aufzubewahren sein. Server-Protokolle richtet der Hostinganbieter nach seinen festgelegten Löschfristen.</p>
<h2>12. Deine Rechte</h2><p>Unter den gesetzlichen Voraussetzungen hast du Rechte auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung der Verarbeitung (Art. 18), Datenübertragbarkeit (Art. 20) und Widerspruch gegen Verarbeitungen auf Grundlage berechtigter Interessen (Art. 21). Eine erteilte Einwilligung kannst du nach Art. 7 Abs. 3 jederzeit mit Wirkung für die Zukunft widerrufen. Außerdem besteht nach Art. 77 DSGVO ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde. Für nicht-öffentliche Stellen in Bayern ist insbesondere das <a href="https://www.lda.bayern.de/de/kontakt.html" target="_blank" rel="noreferrer">Bayerische Landesamt für Datenschutzaufsicht</a>, Promenade 18, 91522 Ansbach, zuständig.</p>
<h2>13. Sicherheit</h2><p>Wir treffen angemessene technische und organisatorische Maßnahmen, um personenbezogene Daten vor Verlust, Manipulation und unbefugtem Zugriff zu schützen. Die Übertragung dieser Website erfolgt verschlüsselt über HTTPS. Eine Internetübertragung kann dennoch nie vollständig risikofrei sein.</p>
<h2>14. Externe Links</h2><p>Beim Anklicken externer Links gelten die Datenschutzbestimmungen des jeweiligen Anbieters. Wir haben keinen Einfluss auf dessen anschließende Datenverarbeitung.</p>
<h2>15. Aktualisierung</h2><p>Wir passen diese Datenschutzerklärung an, wenn sich Funktionen, Dienstleister oder Rechtslagen ändern. Stand: Juli 2026.</p>
<aside>Diese Erklärung bildet die derzeit sichtbaren Funktionen der Website ab. Für einen rechtssicheren Betrieb müssen insbesondere Verträge zur Auftragsverarbeitung, tatsächliche Empfänger, Löschroutinen und gegebenenfalls Drittlandgarantien organisatorisch umgesetzt und dokumentiert werden.</aside></main>}
